services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: host  # раскомментить если проблемы с доступом

  calculation_server:
    build: ./calculation_server
    ports:
      - "11999:11999"
    network_mode: host

  auth:
    build:
      context: .
      dockerfile: Auth/Dockerfile.auth
    container_name: auth_service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=usersauth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    stdin_open: true
    tty: true
    networks:
      - app_network
    profiles:
      - interactive

  calculation_client:
    build:
      context: .
      dockerfile: Client_Server/Dockerfile.client
    container_name: calc_client
    depends_on:
      - calculation_server
    networks:
      - app_network
    profiles:
      - client
    
  qt_client:
    build:
      context: ./Qt_client
      dockerfile: Dockerfile.qt
    container_name: qt_gui
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DISPLAY=host.docker.internal:0.0
      - QT_X11_NO_MITSHM=1
      - QT_IM_MODULE=xim
    networks:
      - app_network
    stdin_open: true
    tty: true

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: