FROM gcc:14

RUN apt-get update && apt-get install -y \
    libpqxx-dev \
    libsodium-dev \
    libcurl4-openssl-dev \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY Auth/ /app/

RUN g++ -std=c++20 -pthread -o auth_tcp_server \
    main_server_auth.cpp auth.cpp database.cpp email_service.cpp \
    -lpqxx -lpq -lsodium -lcurl -lm

EXPOSE 11998
CMD ["./auth_tcp_server"]